version: '3.9'
services:
  db:
    ports:
      - "${DATABASE_PORT:-6432}:5432"

  dev:
    container_name: sawps_dev
    image: kartoza/sanbi:test
    ports:
      # for django test server
      - "61100:8080"
  
  worker:
    image: kartoza/sanbi:test