version: '3.9'
services:
  db:
    ports:
      - "${DATABASE_PORT:-6432}:5432"

  dev:
    image: kartoza/sanbi:test
    volumes:
      - ../django_project:/home/web/django_project
    ports:
      # for django test server
      - "61100:8080"
    command:
      - python
      - manage.py
      - runserver
      - 0.0.0.0:8080

  worker:
    volumes:
      - ../django_project:/home/web/django_project
    image: kartoza/sanbi:test